Repository SUSE-Cloud/socok8s, pull requests merged in 2019-07, with the labels that each got.

#607 doc: deploy_network prerequisite for manual steps
  doc/source/suse-ecp/ose-targets.rst
Labels: needs 1.0 backport

#609 doc: deploy_network prerequisite for manual steps
  doc/source/suse-ecp/ose-targets.rst
Labels: 1.0 backport

#619 Fixing incorrect user names in generated ses_config
  playbooks/roles/common-ses/templates/ses-config.yml.j2
Labels: needs 1.0 backport

#616 doc: add link in reference to VIP var configuration
  doc/source/deployment/configure.rst
  doc/source/deployment/requirements.rst
Labels: needs 1.0 backport

#608 bump osh repo for deploy_osh
  vars/manifest.yml
Labels: bug

#621 [1.0] doc: add resolution for RabbitMQ timing error (SOC-9536)
  doc/source/operations.rst
Labels: 1.0 backport

#627 Make sure shipyard can read the pegleg output
  playbooks/roles/airship-deploy-osh/tasks/main.yml
Labels: bug
