Repository SUSE-Cloud/socok8s, pull requests merged in 2019-08, with the labels that each got.

#650 Allow choosing caasp version
  Jenkinsfile.integration
Labels: CI

#670 SOC-10091 Update docs to reflect current reality
  doc/source/deployment/requirements.rst
  doc/source/deployment/setup-deployer.rst
  doc/source/glossary.rst
  doc/source/reference.rst
Labels: Docs

#562 CI: Publish ARA reports
  Jenkinsfile.integration
Labels: CI

#693 kill the ssh-agent and the end of the run
  Jenkinsfile.integration
Labels: CI

#629 Make airship control plane node count configurable
  playbooks/openstack-caasp_instance.yml
  playbooks/roles/caasp4/templates/inventory-caasp4.yml.j2
  vars/common-vars.yml
Labels: enhancement

#692 Drop venv + remove tox dir + set verbosity to a sane level
  Jenkinsfile.integration
Labels: CI

#695 Remove CaaSP3 notes from the documentation.
  doc/source/deployment/requirements.rst
  doc/source/reference.rst
Labels: Docs

#714 Fix tempest_test_type value
  Jenkinsfile.integration
Labels: CI

#713 Enable tempest by default (SOC-10120)
  Jenkinsfile.integration
Labels: CI

#702 doc: proofread and copyedit learning>kubernetes page
  doc/source/contributor/kubernetes.rst
Labels: Docs

#717 doc: proofread and copyedit learning > airship page
  doc/source/contributor/airship.rst
Labels: Docs

#723 Doc clusterapi png fix
  doc/source/contributor/architecture.png
Labels: Docs

#700 Add log parser to CI
  Jenkinsfile.integration
  log-parser-plugin-rules.txt
Labels: CI
