Repository SUSE-Cloud/socok8s, pull requests merged in 2019-06, with the labels that each got.

#451 Fix the copyright in setup.py
  setup.py
Labels: Needed for TP

#454 Override Armada deployment timeout configuration
  site/soc/deployment/deployment-configuration.yaml
Labels: Needed for TP

#450 Fix conflciting endpoint definition in endpoints.yml for novncproxy
  site/soc/software/config/endpoints.yaml
Labels: Needed for TP

#453 CI: only run lint when playbook files have changed
  Jenkinsfile.integration
Labels: CI

#460 doc: add socok8s installation alternatives
  doc/source/deployment/setup-deployer.rst
Labels: Needed for TP

#456 Update tempest config params to increase smoke test success rate
  doc/source/deployment/verify.rst
  playbooks/roles/airship-deploy-tempest/defaults/main.yml
  playbooks/roles/airship-deploy-tempest/tasks/main.yml
  site/soc/software/charts/osh/openstack-tempest/tempest.yaml
Labels: Needed for TP

#448 Adding note for SES 2 disk requirement for AIO setup.
  doc/source/deployment/requirements.rst
Labels: Needed for TP

#467 Corrected prefix support for general storageclass pool name
  playbooks/roles/airship-configure-ceph/defaults/main.yml
Labels: Needed for TP

#443 Fix Neutron tenant networking
  doc/source/deployment/configure.rst
  examples/workdir/inventory/hosts.yml
  playbooks/roles/airship-configure-worker/tasks/main.yml
  playbooks/roles/airship-deploy-ucp/defaults/main.yml
  site/soc/software/charts/osh/openstack-compute-kit/neutron.yaml
Labels: Needed for TP

#468 Fixed indentation problem in tempest site template
  site/soc/software/charts/osh/openstack-tempest/tempest.yaml
Labels: Needed for TP

#475 Disable tempest cleanup and ensure tempest run always returns 0
  doc/source/deployment/verify.rst
  playbooks/roles/airship-deploy-tempest/tasks/main.yml
  site/soc/software/charts/osh/openstack-tempest/tempest.yaml
Labels: Needed for TP

#477 Apply merged patches as well
  playbooks/roles/dev-patcher/tasks/patch-repos.yml
Labels: Needed for TP

#479 Add 4 known smoke test failures to tempest_blacklist
  playbooks/roles/airship-deploy-tempest/files/tempest_blacklist
Labels: Needed for TP

#482 Fix the ssh issue from compute nodes to deployer during remove comput…
  doc/source/operations.rst
  playbooks/generic-clean_airship.yml
  playbooks/remove_compute.yml
  playbooks/roles/openstack-remove-compute/tasks/main.yml
Labels: Needed for TP

#491 Use newer syntax for search() tests
  playbooks/openstack-update_and_reboot_caasp.yml
  playbooks/roles/airship-configure-caasp/tasks/main.yml
  playbooks/roles/airship-configure-caasp/tasks/privileged-cluster-role-binding.yml
  playbooks/roles/airship-deploy-ucp/tasks/main.yml
Labels: enhancement

#504 jenkins: Sanitize the socok8s enviroment name
  Jenkinsfile.integration
Labels: needs 1.0 backport

#505 [1.0] jenkins: Sanitize the socok8s enviroment name
  Jenkinsfile.integration
Labels: 1.0 backport

#499 Correct openstack_project_network_cidr value in tempest documentation
  doc/source/deployment/verify.rst
Labels: Needed for TP, needs 1.0 backport

#507 [1.0] jenkins: Replace '_' on the ENVNAME as well
  Jenkinsfile.integration
Labels: 1.0 backport

#498 [1.0] doc: add airship-openstack-l3-agent-workers to host entries
  doc/source/operations.rst
Labels: 1.0 backport

#497 doc: add airship-openstack-l3-agent-workers to host entries
  doc/source/operations.rst
Labels: Needed for TP

#502 CI: build docs when they change
  Jenkinsfile.integration
Labels: CI

#506 jenkins: Replace '_' on the ENVNAME as well
  Jenkinsfile.integration
Labels: needs 1.0 backport

#493 [1.0] doc: correct run.sh commands; add required command lines
  doc/source/deployment/configure.rst
  doc/source/deployment/deploy.rst
  doc/source/suse-ecp/ose-deploy.rst
Labels: 1.0 backport, Needed for TP

#490 doc: correct run.sh commands; add required command lines
  doc/source/deployment/configure.rst
  doc/source/deployment/deploy.rst
  doc/source/suse-ecp/ose-deploy.rst
Labels: Needed for TP

#483 Corrected requirements for ISO install.
  doc/source/deployment/setup-deployer.rst
Labels: 1.0 backport, Needed for TP

#511 [1.0] doc: add content about retry file path (SOC-9467)
  doc/source/deployment/configure.rst
Labels: 1.0 backport

#510 [1.0] doc: Correct openstack_project_network_cidr value in tempest documentation
  doc/source/deployment/verify.rst
Labels: 1.0 backport, Needed for TP

#538 Increase airship update action timeout
  playbooks/roles/airship-deploy-osh/tasks/main.yml
Labels: needs 1.0 backport

#531 [1.0] doc: Add documentation for updating OpenStack service configuration
  doc/source/operations.rst
Labels: 1.0 backport, Needed for TP

#540 Increase airship update action timeout
  playbooks/roles/airship-deploy-osh/tasks/main.yml
Labels: 1.0 backport, CI

#514 doc: Add documentation for updating OpenStack service configuration
  doc/source/operations.rst
Labels: Needed for TP, needs 1.0 backport

#530 1.0: Add instruction to select openstack service to install
  doc/source/user/select-openstack-services.rst
Labels: 1.0 backport, Needed for TP

#529 Add instruction to select openstack service to install
  doc/source/user/select-openstack-services.rst
Labels: Needed for TP, needs 1.0 backport

#517 doc: only flat networks are supported.
  doc/source/deployment/requirements.rst
Labels: needs 1.0 backport

#494 [1.0] doc: change uninstall prompt, remove reference to environment variable
  doc/source/deployment/uninstall.rst
Labels: 1.0 backport, Needed for TP

#492 doc: change uninstall prompt, remove reference to environment variable
  doc/source/deployment/uninstall.rst
Labels: Needed for TP, needs 1.0 backport

#489 Adding doc for providing master api node info for DNS
  doc/source/deployment/configure.rst
Labels: Needed for TP, needs 1.0 backport

#528 1.0: Add tech preview disclaimer
  doc/source/index.rst
Labels: Needed for TP

#501 [1.0] doc: add content describing OpenStack services. Minor proofing.
  doc/source/deployment/deploy.rst
  doc/source/deployment/requirements.rst
  doc/source/deployment/setup-deployer.rst
  doc/source/user/select-openstack-services.rst
Labels: 1.0 backport

#500 doc: add content describing OpenStack services. Minor proofing.
  doc/source/deployment/deploy.rst
  doc/source/deployment/requirements.rst
  doc/source/user/select-openstack-services.rst
Labels: Needed for TP

#474 Give useful output if armada-api times out
  playbooks/roles/airship-deploy-ucp/tasks/main.yml
Labels: CI

#558 Switch CI job to provo mirror for Leap
  Jenkinsfile.integration
  playbooks/openstack-osh_hostconfig.yml
  vars/common-vars.yml
  vars/deploy-on-openstack.yml
Labels: needs 1.0 backport

#573 [1.0] Switch to a smaller flavor for SES the instance
  vars/deploy-on-openstack.yml
Labels: 1.0 backport

#569 [1.0] backport some fixes from master
  Jenkinsfile.integration
  playbooks/openstack-osh_hostconfig.yml
  playbooks/openstack-ses_aio_hostconfig.yml
  playbooks/roles/deploy-osh/defaults/main.yml
  vars/common-vars.yml
  vars/deploy-on-openstack.yml
Labels: 1.0 backport

#565 Do not deploy glance with the values intended for Newton
  playbooks/roles/deploy-osh/tasks/main.yml
  vars/common-vars.yml
Labels: needs 1.0 backport

#586 Configurable timeout for airship update action
  playbooks/roles/airship-deploy-osh/defaults/main.yml
  playbooks/roles/airship-deploy-osh/tasks/main.yml
Labels: needs 1.0 backport

#564 CI: Drop travis file
  .travis.yml
Labels: CI

#574 [1.0] Do not deploy glance with the values intended for Newton
  playbooks/roles/deploy-osh/tasks/main.yml
  vars/common-vars.yml
Labels: 1.0 backport
