Repository SUSE-Cloud/socok8s, pull requests merged in 2019-09, with the labels that each got.

#734 Bump the worker flavors
  playbooks/roles/caasp4/defaults/main.yml
Labels: CI

#726 Add dstat to caasp workers
  Jenkinsfile.integration
  playbooks/generic-gather_dstat_output.yml
  playbooks/kvm-deploy_caasp.yml
  playbooks/openstack-deploy_caasp.yml
  playbooks/roles/dstat/defaults/main.yml
  playbooks/roles/dstat/tasks/fetch-data.yml
  playbooks/roles/dstat/tasks/main.yml
  script_library/deployment-actions-common.sh
  script_library/deployment-actions-openstack.sh
Labels: CI

#721 Allow keeping the CI machines after the run
  Jenkinsfile.integration
Labels: CI, Dont merge

#746 Retry teardown on CI
  Jenkinsfile.integration
Labels: CI

#747 retry terraform destroy
  playbooks/roles/caasp4/tasks/cleanup_nodes.yml
Labels: CI

#476 Catch more failure messages
  playbooks/roles/airship-deploy-osh/tasks/main.yml
Labels: CI

#732 Parse subunit output from tempest into junit
  Jenkinsfile.integration
  playbooks/generic-tempest-output-to-junit.yml
  playbooks/roles/airship-deploy-tempest/defaults/main.yml
  playbooks/roles/airship-deploy-tempest/tasks/main.yml
  run.sh
  script_library/deployment-actions-common.sh
  script_library/deployment-actions-kvm.sh
  script_library/deployment-actions-openstack.sh
  script_library/pre-flight-checks.sh
  site/soc/software/charts/osh/openstack-tempest/tempest.yaml
Labels: CI

#756 Blacklist known failing tempest tests
  playbooks/roles/airship-deploy-tempest/files/tempest_blacklist
Labels: CI, Dont merge

#762 Adapt the kubectl get command to get just name of the nodes
  playbooks/roles/deploy-osh/tasks/enroll-caasp-nodes-for-osh.yml
Labels: 503 error

#745 Disable helm test containers on CI
  Jenkinsfile.integration
  playbooks/roles/airship-deploy-ucp/defaults/main.yml
Labels: CI

#781 Use dev patcher to patch keystone chart, fixes 503 (SOC-10514)
  playbooks/roles/airship-deploy-ucp/tasks/main.yml
  playbooks/roles/dev-patcher/defaults/main.yml
  site/soc/software/charts/osh/openstack-keystone/keystone.yaml
  site/soc/software/config/endpoints.yaml
  site/soc/software/config/versions.yaml
Labels: CI
